modLoader="javafml"
loaderVersion="[58,)"
license="MIT"

issueTrackerURL="https://github.com/gta66666668/Endpoem/issues"

[[mods]]
modId="endpoemforge"
version="1.0.3"
displayName="Endpoem"
authors="gta66666668"

displayURL="https://github.com/gta66666668/Endpoem"

logoFile="assets/endpoemforge/icon.png"
description='''Adds /endpoem command to replay the End Poem.'''

[[dependencies.endpoemforge]]
modId="forge"
mandatory=true
versionRange="[58,59)"
ordering="NONE"
side="BOTH"

[[dependencies.endpoemforge]]
modId="minecraft"
mandatory=true
versionRange="[1.21.8,1.22)"
ordering="NONE"
side="BOTH"
